program Project13_Server;

uses
  Vcl.Forms,
  FrmExam in 'Exam\FrmExam.pas' {fExam},
  FrmExercise in 'Exercise\VCL\FrmExercise.pas' {fExercise},
  FrmLoadForm in 'Frame\FrmLoadForm.pas' {fLoadform},
  FrmMain in 'Frame\FrmMain.pas' {fMain},
  FrmLog in 'Log\FrmLog.pas' {fLog},
  FrmPaper in 'Paper\FrmPaper.pas' {fPaper},
  FrmTrain in 'Training\FrmTrain.pas' {fTrain},
  FrmOption in 'Option\FrmOption.pas' {fOption},
  FrmOptionBase in 'Option\FrmOptionBase.pas' {fOptionBase},
  FrmErrorSelect in 'WiringError\FrmErrorSelect.pas' {fErrorSelect},
  xWiringError in '..\..\..\FMX_Pub_src\ElectricityMeter\xWiringError.pas',
  FrmWEDetails2 in 'WiringError\WiringError\FrmWEDetails2.pas' {fWEDetails2},
  U_DIAGRAM_TYPE in 'WiringError\WiringError\U_DIAGRAM_TYPE.pas',
  U_WE_EQUATION in 'WiringError\WiringError\U_WE_EQUATION.pas',
  U_WE_EQUATION_DRAW in 'WiringError\WiringError\U_WE_EQUATION_DRAW.pas',
  U_WE_EQUATION_MATH in 'WiringError\WiringError\U_WE_EQUATION_MATH.pas',
  U_WE_EXPRESSION in 'WiringError\WiringError\U_WE_EXPRESSION.pas',
  U_WIRING_ERROR in 'WiringError\WiringError\U_WIRING_ERROR.pas',
  U_POWER_LIST_INFO in 'WiringError\WiringError\AnalysisMap\U_POWER_LIST_INFO.pas',
  U_WE_ORGAN in 'WiringError\WiringError\V2\U_WE_ORGAN.pas',
  U_WE_VECTOR_EQUATION in 'WiringError\WiringError\V2\U_WE_VECTOR_EQUATION.pas',
  U_WE_VECTOR_MAP in 'WiringError\WiringError\V2\U_WE_VECTOR_MAP.pas',
  U_WE_DIAGRAM2 in 'WiringError\WiringError\U_WE_DIAGRAM2.pas',
  U_WE_PHASE_MAP in 'WiringError\WiringError\U_WE_PHASE_MAP.pas',
  U_WE_POWER_ANALYSIS in 'WiringError\WiringError\U_WE_POWER_ANALYSIS.pas',
  U_ERRORF_TO_WIRING in 'WiringError\U_ERRORF_TO_WIRING.pas',
  FrmQInfoC in 'Question\FrmQInfoC.pas' {fQInfo},
  xDBConn in '..\..\..\FMX_Pub_src\VCL\xDBConn.pas',
  xQuestionAction in '..\..\..\FMX_Pub_src\Question\xQuestionAction.pas',
  xQuestionInfo in '..\..\..\FMX_Pub_src\Question\xQuestionInfo.pas',
  xSortAction in '..\..\..\FMX_Pub_src\Question\xSortAction.pas',
  xSortControl in '..\..\..\FMX_Pub_src\Question\xSortControl.pas',
  xSortInfo in '..\..\..\FMX_Pub_src\Question\xSortInfo.pas',
  xConsts in '..\..\..\FMX_Pub_src\xConsts.pas',
  xDBActionBase in '..\..\..\FMX_Pub_src\xDBActionBase.pas',
  uQuestionInfo in '..\..\..\FMX_Pub_src\Question\VCL\uQuestionInfo.pas' {fQuestionInfo},
  uQuestionList in '..\..\..\FMX_Pub_src\Question\VCL\uQuestionList.pas' {fQuestionList},
  uSortInfo in '..\..\..\FMX_Pub_src\Question\VCL\uSortInfo.pas' {fSortInfo},
  uSortList in '..\..\..\FMX_Pub_src\Question\VCL\uSortList.pas' {fSortList},
  FrmQuestionListC in 'Question\FrmQuestionListC.pas' {fQuestionListC},
  xVCL_FMX in '..\..\..\FMX_Pub_src\VCL\xVCL_FMX.pas',
  Vcl.Themes,
  Vcl.Styles,
  xStudentAction in '..\..\..\FMX_Pub_src\Student\xStudentAction.pas',
  xStudentControl in '..\..\..\FMX_Pub_src\Student\xStudentControl.pas',
  xStudentInfo in '..\..\..\FMX_Pub_src\Student\xStudentInfo.pas',
  xStudentTabelOutOrIn in '..\..\..\FMX_Pub_src\Student\xStudentTabelOutOrIn.pas',
  uStudentInfo in '..\..\..\FMX_Pub_src\Student\VCL\uStudentInfo.pas' {fStudentInfo},
  uStudentList in '..\..\..\FMX_Pub_src\Student\VCL\uStudentList.pas' {fStudentList},
  xFunction in '..\..\..\FMX_Pub_src\xFunction.pas',
  xExerciseInfo in 'Exercise\xExerciseInfo.pas',
  xExerciseAction in 'Exercise\xExerciseAction.pas',
  xExerciseControl in 'Exercise\xExerciseControl.pas',
  FrmPosState in 'Exam\FrmPosState.pas' {fPosState},
  xClientInfo in 'Exam\xClientInfo.pas',
  xExamControl in 'Exam\xExamControl.pas',
  FrmRanking in 'FrmRanking.pas' {fRanking},
  xTypes in '..\..\..\FMX_Pub_src\xTypes.pas',
  xCommBase in '..\..\..\FMX_Pub_src\Comm\xCommBase.pas',
  xSerialBase in '..\..\..\FMX_Pub_src\Comm\xSerialBase.pas',
  xTCPClientBase in '..\..\..\FMX_Pub_src\Comm\xTCPClientBase.pas',
  xTCPServerBase in '..\..\..\FMX_Pub_src\Comm\xTCPServerBase.pas',
  xUDPServerBase in '..\..\..\FMX_Pub_src\Comm\xUDPServerBase.pas',
  xThreadBase in '..\..\..\FMX_Pub_src\xThreadBase.pas',
  xProtocolBase in '..\..\..\FMX_Pub_src\xProtocolBase.pas',
  xClientType in 'Exam\xClientType.pas',
  xTCPServer in 'TCP\xTCPServer.pas',
  xThreadUDPSendScreen in 'SendScreen\xThreadUDPSendScreen.pas',
  FrmExamineeList in 'Exam\FrmExamineeList.pas' {fExamineeList},
  xDataDictionary in '..\..\..\FMX_Pub_src\xDataDictionary.pas',
  xExamInfo in '..\..\..\FMX_Pub_src\Exam\xExamInfo.pas',
  uExamInfo in '..\..\..\FMX_Pub_src\Exam\uExamInfo.pas' {fExamInfo},
  uTestData in 'Answer\TestData\uTestData.pas' {fTestData},
  xTestDataInfo in 'Answer\TestData\xTestDataInfo.pas',
  FrmVectorMapInfo in 'Answer\VectorMap\FrmVectorMapInfo.pas' {fVectorMapInfo},
  U_VECTOR_CONTROL in 'Answer\VectorMap\U_VECTOR_CONTROL.pas',
  U_VECTOR_LIEN_INFO in 'Answer\VectorMap\U_VECTOR_LIEN_INFO.pas',
  xUDPServer in 'UDP\xUDPServer.pas',
  xProtocolSendScreen in 'SendScreen\xProtocolSendScreen.pas',
  xTrainQuestionInfo in 'Training\xTrainQuestionInfo.pas',
  xTrainQuestionAction in 'Training\xTrainQuestionAction.pas',
  xTrainQuestionControl in 'Training\xTrainQuestionControl.pas',
  FrmAbout in '..\..\..\FMX_Pub_src\About\VCL\FrmAbout.pas' {fAbout};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TfMain, fMain);
  Application.CreateForm(TfAbout, fAbout);
  Application.Run;
end.
